# Generated by Django 3.2.22 on 2023-12-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../django-rest-framework/default_profile_vug5i3', upload_to='images/'),
        ),
    ]
