# Generated by Django 3.2.22 on 2023-12-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_fgimrx', upload_to='images/'),
        ),
    ]
